#pragma once
#include "esp_system.h"

enum {
	LED_UPDATE_SUCCESS=1,
	LED_UPDATE_FAIL,
	LED_UPDATING,
	LED_PAIRING_ACTIVED,
	LED_WIFI_DISCONNECTED,
	LED_WIFI_CONNECTED,
	LED_WIFI_GOT_IP,
	LED_BUTTON_PRESSED_PRE_PAIRING,
	LED_WIFI_CLOUD_CONNECTED,
	LED_PAIRING_CONNECTED,
	LED_BUTTON_PRESSED_PAIRING,
	LED_BUTTON_PRESSED_RESET,
	LED_RESET_ACTIVED,
	LED_DATA_BLINK,
	LED_UWB_COMMUNICATION_FAIL,
};
void led_handler(uint8_t led_state);

void led_init(void);
